### ISSUE TITLE
Switch value is not passed on form submission

### ISSUE THREAD

**Issue by jwbennet** [indiana-university/rivet-switch#4]
I talked with @levimcg about this a bit already, but since the switch uses a button its value will not be included in the form submission unless that button is what submits the form.  I'm thinking you may need to consider supporting a different input element for this when the field needs to be submitted within a form.

**Comment by jolamar** [comment]
Reading this article https://inclusive-components.design/toggle-button/

> The trouble with using form elements is their longstanding association with the collection of data. That is, checkboxes and radio buttons are established as controls for designating values. When a user checks a checkbox, they may just be switching a state, but they may suspect they are also choosing a value for submission.

I think checkboxes should be used for a form where data is collected and a switch should be used ad-hoc to switch state for a user but not necessarily assigning a value for submission. A good example of the switch is on security center the external email switch (no submission required). 

@levimcg @jwbennet thoughts? If you agree then I think we just need better documentation on when to use a switch vs when to use a checkbox/radio input

**Comment by levimcg** [comment]
@jolamar These are some good points. I relied pretty heavily on the article you mention when I was design/building the switch. I agree that maybe this could be solved with some better documentation (switch vs. checkbox, etc.).

I'm also open to the idea of including CSS for a checkbox version of the switch if we decide it's absolutely necessary, but I agree with idea that a switch should probably be reserved for changing some sort of state, or kicking off async requests to the server like you mention, rather than submitting data with a form.

**Comment by mtwagner** [comment]
I second the CSS Checkbox/Radio version idea.

**Comment by jwbennet** [comment]
I think I understand where you are coming from after reading through that article and this one:

https://www.nngroup.com/articles/toggle-switch-guidelines/

I like the table near the start of this article because it succinctly summarizes when you should consider using a radio/checkbox group/single checkbox/toggle.  It definitely seems like some additional documentation on when the switch should be used would be best and maybe it should be explicit that it should likely not be used in a form.

**Comment by jolamar** [comment]
Good find @jwbennet Yes it's that immediacy that toggles offer that I think we need to honor.

**Comment by zttodd** [comment]
This is similar to #3. We will be updating the documentation to reflect best practices. We will close this issue given the similarities.
