### ISSUE TITLE
Custom text for On/Off displayed text. 

### ISSUE THREAD

**Issue by mtwagner** [indiana-university/rivet-switch#5]
It would be nice to have custom text in the switch, ie "Active" and "Inactive".

Due to variable width of possible text, only the selected text would display with the "toggle" to the opposite side, and the non-selected text would be completely obscured.

**Comment by zttodd** [comment]
Given the variability of word length, this would require a redesign of the current functionality. Because of the binary nature of switches, we will be updating the documentation to provide further guidance about labelling. See issue #3.
